package it.unibo.scall
package ast

import grammar.Element.{Nonterminal, TerminalOrEoi}
import lexer.Token

/** Represents a node in the Concrete Syntax Tree (CST) generated by the parser.
 *  It can be a structural rule (nonterminal), a leaf (terminal), or an error node.
 */
enum CSTNode:
  case RuleNode(symbol: Nonterminal, children: Seq[CSTNode])
  case LeafNode(token: Token)
  case ErrorNode(expected: Set[TerminalOrEoi], discarded: Seq[Token])

object Extractors:
  object Rule:
    def unapply(node: CSTNode): Option[(String, Seq[CSTNode])] = node match
      case CSTNode.RuleNode(symbol, children) => Some((symbol.name, children))
      case _                               => None

  object RuleSeq:
    def unapplySeq(node: CSTNode): Option[(String, Seq[CSTNode])] = node match
      case CSTNode.RuleNode(symbol, children) => Some((symbol.name, children))
      case _                               => None

  object Leaf:
    def unapply(node: CSTNode): Option[String] = node match
      case CSTNode.LeafNode(token) => Some(token.lexeme)
      case _                       => None
