package it.unibo.scall
package util

// noinspection ScalaWeakerAccess
object CollectionUtils:

  extension [A](self: Set[Seq[A]])
    /** Returns a new set where the provided value is appended to each element. */
    infix def eachAppend(e: A): Set[Seq[A]] =
      self.map(_ appended e)
    /** Returns a new set containing all possible combinations of elements from this set
     *  concatenated with elements from the other set. */
    infix def productConcat(other: Set[Seq[A]]): Set[Seq[A]] =
      for
        x <- self
        y <- other
      yield x concat y

  extension [K](self: Set[K])
    /** Creates a map whose keys are the elements of this set and whose values
     *  are generated by applying the given function to each key. */
    def associateWith[V](valueSelector: K => V): Map[K, V] =
      self.map(k => k -> valueSelector(k)).toMap

  type MultiMap[K, V] = Map[K, Set[V]]

  extension [K, V](self: MultiMap[K, V])
    /** Returns the set associated with this key if it is present or the empty set otherwise. */
    def getOrEmpty(key: K): Set[V] =
      self.getOrElse(key, Set.empty)
    /** Returns a new multimap by merging the two maps. If a key is present in both maps,
     *  the resulting value is the union of the two associated sets. */
    infix def unionAll(other: MultiMap[K, V]): MultiMap[K, V] =
      val keys = self.keySet union other.keySet
      keys.associateWith(k => self.getOrEmpty(k) union other.getOrEmpty(k))
    /** Returns the result of applying the given function to each entry, that is,
     *  each pair consisting of a key and one of the elements of its associated set.
     */
    def mapEntries[B](mapper: (K, V) => B): Iterable[B] =
      self.flatMap((k, v) => v.map(mapper(k, _)))
    /** Returns the collection of all entries, as defined in [[mapEntries]]. */
    def flattenEntries: Iterable[(K, V)] =
      self.mapEntries(_ -> _)
